esphome:
  name: gas-counter
  friendly_name: Gas_Counter

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YOUR API KEY "

  services:
    - service: gesamtanzahl_impulse_ha
      variables:
        gesamtanzahl_impulse_ha: int
      then:
        - globals.set:
            id: gesamtanzahl_impulse
            value: !lambda 'return gesamtanzahl_impulse_ha;'

ota:
  platform: esphome
  password: "YOUR PASSWORD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gas-Counter Fallback Hotspot"
    password: " YOUR FALLBACK PASSWORD"

captive_portal:

globals:
    - id: gesamtanzahl_impulse
      type: int
      restore_value: false



sensor:
  - platform: wifi_signal
    name: None
    update_interval: 3s
    icon: 'mdi:wifi'

  - platform: pulse_counter
    pin: GPIO14
    name: "Gas Impuls"
    unit_of_measurement: 'Impulse'
    id: gas_puls
    internal_filter: 150ms

    total:
      unit_of_measurement: 'm³'
      name: 'Gas total'
      id: gas_puls_total
      device_class: gas
      accuracy_decimals: 2
      filters:
        - multiply: 0.01  # (1/100 pulses per m³)
  
  - platform: copy
    source_id: gas_puls_total
    name: "Total Impulse Gas"
    accuracy_decimals: 0
    filters:
        - multiply: 100  


# Example SNTP
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin
    servers:
     - 192.168.xxx.xxx                      # Edit SNTP Server like a Fritzbox or...

 # - platform: template
 #   name: "Gas Total m3"
 #   lambda: |-
 #     return id(gesamtanzahl_impulse) * 0.01;
 #   unit_of_measurement: "m³"
 #   state_class: total_increasing
 #   accuracy_decimals: 2
 #   device_class: gas
 #   icon: 'mdi:fire'
 #   update_interval: 60s

  #- platform: template
  #  name: "Gas m³ used"
  #  lambda: !lambda 'return id(gesamtanzahl_impulse);'
  #  unit_of_measurement: "m³/min"
  #  device_class: gas
  #  accuracy_decimals: 0
  #  icon: 'mdi:fire'
  #  update_interval: 60s
